### PR TITLE
update to work with latest discord api and other misc fixes

### PR DESCRIPTION
**Pull request by UpcraftLP**
- updated dependencies
- updated repository URL in metadata
- added missing ApplicationCommandOptionType options
- added resolved data to interaction context (needed for ex. file attachment arguments)
- made discord API BASE_URL public so it can be used outside the crate
- made it so people can run their own independent web server and only redirect specific paths to this crate's interaction handler, instead of being forced to use this crate's default implementation
- misc fixes
- bump version to `0.3.0`

> [!IMPORTANT]
> Note that this PR does NOT address updating the test or examples files

### CODE REVIEW

**Comment by showengineer** [comment]
Nice! I am surprised the core of this crate still works after 2 years of not being developed (something with getting into university and getting a job, no time for hobby projects) . I'll look at your PR tonight.

**Comment by UpcraftLP** [comment]
Yeah it is very robust, and tbh I was simply too lazy to reimplement discord interactions 😅

And dw I know the grind.. To be honest I did not expect to get a response at all, so I'm positively surprised ^^

**Comment by showengineer** [comment]
PR looks good. We do have to update the examples but that seems like a quick fix. I'll check if I can fix that before merging.

**Comment by UpcraftLP** [comment]
fwiw
- [here](https://github.com/UpcraftLP/winterjam-mc-link/blob/6dc94dcec9dc020fcb064b66bdc638badd2bb27c/api/src/server.rs#L75-L88) is also how I'm using the crate with a separate web server
- and [here](https://github.com/UpcraftLP/picturebot-rs/blob/684cd2d4f15cfa5a89beb7a168caccb5b34830d7/src/discord/commands/upload.rs) is how I'm handling attachments.

Those feel like they could use additional examples/documentation for new users ^^

**Comment by showengineer** [comment]
Nice! I was more or less referring to the current tests though, they fail atm.

**Comment by UpcraftLP** [comment]
Yeah I know. as stated in the original message I didn't touch those at all, so ofc they would break 😅

**Comment by showengineer** [comment]
The examples build fail somehow in the CI but I can't reproduce them on my own machine. Is that the same for you?

**Comment by showengineer** [comment]
You know what f*ck it. I am merging this and we'll see if it breaks after merging.

**Comment by UpcraftLP** [comment]
> The examples build fail somehow in the CI but I can't reproduce the errors on my own machine. They run and compile just fine. Is that the same for you?

no they very much fail to compile for me (as would be expected)

**Pull request merged**
